StackStorm/ansible-st2

- README.md
- circle.yml
- roles/mistral/tasks/install_deps.yml
- roles/st2/tasks/4.dependencies.yml
Partially solves #7 
While the initial plan was bigger: Rspec Integration tests, Test-Kitchen, isolation, different linux distros to test,
it could be good to postpone it because of upcoming changes in st2 packaging and testing.
This PR includes very basic Playbook run under CircleCI.com (Circle is faster than Travis).
Good enough for current needs when playbooks only support Ubuntu. Progress in small steps.
So here we just check if playbook run is succeeded under Ubuntu 12.
-----
Not to forget: 
* CircleCI supports Docker
* [Travis now supports Docker too](http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/)
* KitchenCI:
* [kitchen-docker](https://github.com/portertech/kitchen-docker)
* [kitchen-vagrant](https://github.com/test-kitchen/kitchen-vagrant)
* …
> Minimal CI tests

- roles/mistral/tasks/install_deps.yml
Fixes
```
TASK: [mistral | Install requirements] ****************************************
failed: [localhost] => {"failed": true}
msg: Failed to find required executable virtualenv 
```
> Include pip virtualenv in mistral install

- roles/st2/tasks/4.dependencies.yml
Installing st2 fails on 'Install st2 pip dependencies' with 'Upgrade pip, your version `1.5.4' is outdated'
Tested with the ubuntu/trusty64 box, version 20150928.0.0
> Upgrade pip

- circle.yml
- roles/mistral/meta/main.yml
Fixes #27 
Also make sure Ansible version is >= 1.9.1 for this flag to work properly, see bug: https://github.com/ansible/ansible/issues/10550
> Add sudo flag for ANXS.postgresql role

- roles/mistral/tasks/install_mistral.yml
Mistral wouldn't start on a clean vagrant box because the log dir didn't exist. This should solve that issue.
> Ensure that the /var/log/mistral dir exists

- roles/mistral/defaults/main.yml
- roles/mistral/tasks/gather_facts.yml
`version` is **very** generic variable name for mistral version, resulting bugs reported in #community by @johandahlberg.
Avoid collisions, rename it.
> Rename `version` to `mistral_version`

- roles/mistral/defaults/main.yml
- roles/mistral/tasks/gather_facts.yml
- roles/mistral/tasks/sync.yml
I added a prefix to the mistral version, and I also added a `touch /etc/mistral/database_setup.lock` to make sure that the database is not populated twice.
> Fixed problems in installing mistral

- roles/mistral/defaults/main.yml
- roles/mistral/files/mistral.conf
- roles/mistral/meta/main.yml
- roles/mistral/tasks/config.yml
- roles/mistral/templates/mistral.conf.j2
- roles/st2/defaults/main.yml
- roles/st2/tasks/2.version.yml
- roles/st2/tasks/3.user.yml
Two small fixes:
- If the `st2_revision` was not set to `current` `_st2_revision` was not set and thus failed downstream.
- Made it possible to configure some of the values for mistral, i.e. the password, server and db values.
> Revision can be set manually and mistral config fixes

- README.md
Note in README that current StackStorm deployment with Ansible is outdated, entire installation logic will be changed without migration support from `old` -> `new`.
> BC/Outdated Notice [ci skip]

- roles/st2/tasks/main.yml
Minor fix to use the correct syntax when specifying version revisions to apt.
> Use correct APT syntax for specifying version revisions

- circle.yml
> ```Error: Port conflict: another instance is already running on /var/run/postgresql with port 5432   ...fail!```
Purge postgresql installations, making sure we don't have postgresql running/binding on default port.
We can do that, after switching to different CircleCI ubuntu14.04 container.
> Fix build status

- circle.yml
- roles/mongodb/tasks/main.yml
> Work on #49 
Since [StackStorm v1.6](https://stackstorm.com/2016/08/10/stackstorm-v1-6-0/), MongoDB `3.2` is the default supported version.
> Switch to MongoDB 3.2 packages

- roles/mistral/tasks/main.yml
- roles/st2/tasks/user.yml
Enable per task pipelining to fix issue with Ansible 2.1 [1], otherwise it
would faile with "Failed to set permissions on the temporary files
Ansible needs to create when becoming an unprivileged user."
[1] https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"
> Fix Ansible 2.1 become-unprivileged-user compatibility issue

- .kitchen.yml
- playbooks/requirements.yml
- roles/mistral/meta/main.yml
Discovered in https://github.com/StackStorm/ansible-st2/pull/54
```sh
TASK [ANXS.postgresql : PostgreSQL | Make sure the PostgreSQL users are present] ***
task path: /tmp/kitchen/roles/ANXS.postgresql/tasks/users.yml:8
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode object' has no attribute 'name'\n\nThe error appears to have been in '/tmp/kitchen/roles/ANXS.postgresql/tasks/users.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: PostgreSQL | Make sure the PostgreSQL users are present\n  ^ here\n"}
```
This is probably due to newer Ansible and older dependency.
Try to …
> Fix PostgreSQL build failure

- roles/mistral/meta/main.yml
- roles/mistral/requirements.yml
See: https://github.com/StackStorm/ansible-st2/pull/55
Thanks @jvrplmlmn for pointing to that!
It looks even more messed. Latest ANXS.postgresql on GitHub is `v1.6.2`, while latest released on Galaxy is `v1.5.0`.
Pinning to version on galaxy.
> Update ANXS.postgresql for real

- .kitchen.yml
- playbooks/requirements.yml
So `ANXS.postgresql` role works with latest Ansible `v2.2.0`.
Back to normal.
> Unpin Ansible version

- README.md
Ubuntu Xenial packages are officially available since StackStorm `v2.1`: https://stackstorm.com/2016/12/06/2-1-new-pack-management/
> Add official support for Ubuntu Xenial (16.04)

- .kitchen.yml
https://github.com/StackStorm/ansible-st2/pull/59 Ubuntu Xenial packages are now available in `stable` repo.
> Use stable packagecloud repo for CI

- roles/rabbitmq/meta/main.yml
- roles/rabbitmq/tasks/main.yml
Output:
```
TASK [rabbitmq : Install rabbitmq packages on CentOS] **************************
changed: [default]
RUNNING HANDLER [rabbitmq : restart rabbitmq] **********************************
changed: [default]
```
>  Rhel support: rabbitmq-server

- Vagrantfile
Reference: https://github.com/StackStorm/ansible-st2/issues/67
> Vagrantfile update for Multi VM support

- roles/rabbitmq/tasks/main.yml
Just a small addition to check that `rabbitmq-server` service is enabled and started which is usually a [good practice](http://docs.ansible.com/ansible/playbooks_best_practices.html#task-and-handler-organization-for-a-role) after installing some service.
The thing I missed in https://github.com/StackStorm/ansible-st2/pull/70
> Ensure rabbitmq is enabled and running

- meta/main.yml
Meta which allows installing `ansible-st2` repo via ansible-galaxy
```sh
ansible-galaxy install ...
```
And while `ansible-st2` is not a real single "role", since we store many roles in `roles/`, this workaround for `ansible.cfg` to find stackstorm roles in plays should work:
```ini
[defaults]
roles_path = /etc/ansible/roles/:/etc/ansible/roles/stackstorm/roles/
```
> Include meta for Galaxy install

- .kitchen-docker/centos6/Dockerfile
- .kitchen.yml
- .travis.yml
> Implements https://github.com/StackStorm/ansible-st2/issues/69
Enable CI for `CentOS6` (`kitchen-docker` in TravisCI).
Additionally, we run the task with `allow_failures` in Travis until CentOS6 is fully supported by `ansible-st2` playbooks as part of https://github.com/StackStorm/ansible-st2/milestone/2 plan.
> Enable CI for CentOS6

- .kitchen-docker/centos7/Dockerfile
- .kitchen.yml
- .travis.yml
This implements #68 
Enable CI for `CentOS7` (`kitchen-docker` in TravisCI).
Allow CentOS7 build to fail in Travis until we fully implement platform support in Ansible playbooks as part of https://github.com/StackStorm/ansible-st2/milestone/2 plan.
> Enable CentOS7 CI in Travis

- .kitchen.yml
- roles/st2smoketests/tasks/main.yml
This PR enables Idempotence check in `Kitchen-Ansible` CI and closes #6.
It verifies that second playbook re-run ends with `changed=0 failed=0` result.
I'm glad this happened, since we removed external `ANXS.postgresql` dependency role :tada: 
Thanks to @humblearner PRs, everything is already prepared for this transition, I just had to enable the check and mark `st2smoketests` as changed: no.
> Enable Idempotence check

- README.md
- roles/st2/defaults/main.yml
- roles/st2/tasks/main.yml
- roles/st2mistral/defaults/main.yml
- roles/st2mistral/tasks/main.yml
- roles/st2web/tasks/main.yml
This PR changes the naming to install latest StackStorm version.
`st2_version=stable`
to install latest version of `st2`
`st2_version=latest`
to install latest version of `st2`.
This is more user-friendly and doesn't collide with `st2_pkg_repo=stable`.
---
The reason why it was `stable` before comes from history with old `st2_deploy.sh` script: https://github.com/StackStorm/st2/blob/ed6fdb4043647b766551c25f365782a58abce019/tools/st2_deploy.sh#L112-L113
Use better and more clear and obvious naming now.
> Change default value to install Stackstorm latest

- roles/mongodb/tasks/mongodb_apt.yaml
- roles/mongodb/tasks/mongodb_yum.yaml
- roles/st2repos/tasks/main.yml
`update_cache` is equivalent of `apt-get/yum upgrade`.
With that flag set to `yes` we get "changed" state for task on playbook re-run (bad): 
```yaml
TASK [st2repos : Install prereqs] **********************************************
changed: [test.uswest2.stackstorm.net] => (item=[u'debian-archive-keyring', u'apt-transport-https'])
```
So we `update_cache` when adding repository and don't `update_cache` when installing the package itself.
> Don't update cache during package installs

- roles/nginx/meta/main.yml
- roles/nginx/tasks/nginx_yum.yml
- stackstorm.yml
Fixes the following error under `EL 6/7`: 
```yaml
TASK [nginx : Allow network access for nginx] **********************************
task path: /tmp/kitchen/roles/nginx/tasks/nginx_yum.yml:34
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "SELinux is disabled on this host."}
```
Also includes other cosmetic changes for `nginx` role.
> Fix Selinux module work for nginx role

- roles/st2/tasks/user.yml
The current `st2` role does not disable the "requiretty" option in `/etc/sudoers`, which is a required step for setting up stackstorm, and as a result, the `st2smoketest` role was failing when it was time to run st2 commands:
```
[ec2-user@ip-10-0-4-218 ~]$ st2 run core.local_sudo -- date -R
.
id: 58866ee4ddd8ff29343e2d1b
status: failed
parameters:
cmd: date -R
result:
failed: true
return_code: 1
stderr: 'sudo: sorry, you must have a tty to run sudo'
stdout: ''
succeeded: false
[ec2-user@ip-10-0-4-218 ~]$
```
This PR introduces this step in the configuration.
> Added step to disable requiretty

- roles/st2smoketests/tasks/main.yml
The previous variable resulted in a hostname that was unknown to the remote node, (at least when running in AWS) and this test failed.
Since this test is intended to take place on the node where stackstorm is installed/running, localhost should work fine.
> Changed webui smoke test to simply use localhost

- roles/postgresql/tasks/main.yml
Actual error:
```
FAILED! => {"failed": true, "reason": "the file_name '...roles/postgresql/tasks/postgresql_apt.yml' does not exist, or is not readable"}
```
> Fix task include in postgresql role

- README.md
- roles/st2/defaults/main.yml
- roles/st2/tasks/auth.yml
Save user credentials for `root` in `/root/.st2/config` as [installer script does](https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-deb.sh#L397-L401)
It is convenient to have the system ready-to-use after install, but if one doesn't like it, turn off by `st2_save_credentials: no`.
> Save credentials in .st2/config file

- roles/st2/tasks/user.yml
- roles/st2mistral/tasks/main.yml
Bringing back fix https://github.com/StackStorm/ansible-st2/commit/11129e980327ac9f32d108ce129abef66cc3612f
Currently hitting error:
~~~
TASK [st2 : user | Authorize key-based access for system user] *****************
fatal: [10.254.2.12]: FAILED! => {"failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs t                           o create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/tmp/ansible-tmp-1485779578.73-1856                           62873622578/': Operation not permitted\nchown: changing ownership of '/tmp/ansible-tmp-1485779578.73-185662873622578/autho                           rized_key.py': Operation not permitted\n). For information on working around this, see https://docs.ansible.com/ansible/be …
> Re-Enabling per task pipelining

- roles/st2mistral/tasks/main.yml
> Partially fixes https://github.com/StackStorm/ansible-st2/issues/103#issuecomment-275851955
If `mistral-db-manage` failed first time, - it's skipped on next playbok re-run. This is wrong behavior.
This caused by blocking conditions in `when:`, - they are removed now.
> Fix mistral register re-run on failure

- roles/nginx/tasks/main.yml
- roles/nginx/tasks/nginx_apt.yml
- roles/nginx/tasks/nginx_yum.yml
- roles/st2web/tasks/main.yml
The logic of creating `available` and `enabled` virtualhost dirs should be part of `nginx` role itself, not `st2web`.
Theoretically we could re-use `nginx` role in future.
> Move virtualhost dirs management from `st2web` to `nginx` role

- roles/st2mistral/tasks/main.yml
Init of git is added here to temporarily fix a bug in python-muranoclient during pbr version checking on OpenStack action generations.
> Fix to circumvent pbr related bug in mistral-db-manage populate

- .kitchen.yml
- .travis.yml
As sugested by @dzimine in https://github.com/StackStorm/ansible-st2/issues/103, adding `unstable` PackageCloud repo to the Travis Build Matrix.
This will force us to pick up `st2`/`st2mistral` package configuration fixes early.
> Unstable repo in Build matrix

- .kitchen-docker/centos6/Dockerfile
- .kitchen-docker/centos7/Dockerfile
- .kitchen.yml
Revert temporary workaround from https://github.com/StackStorm/ansible-st2/pull/82#discussion_r96282814 to use `root` in CentOS7 docker container.
It's possible since we're building `packagingtest` https://hub.docker.com/r/stackstorm/packagingtest/ Docker images automatically on every push to [st2-dockerfiles](https://github.com/StackStorm/st2-dockerfiles/tree/master/packagingtest) repo and can fix upstream images more easily.
See: https://github.com/StackStorm/st2-packages/pull/417 and https://github.com/StackStorm/st2-dockerfiles/issues/38 for more info
> Update CentOS Docker images endpoints

- .travis.yml
Tiny change to remove duplicated `DISTRO`s from `.travis.yml` previously added by mistake.
> Remove duplicated distros from .travis.yml

- roles/st2mistral/tasks/main.yml
Reverts StackStorm/ansible-st2#109 temporary workaround.
Follow-up: https://github.com/StackStorm/st2-packages/pull/416 since bug is fixed in upstream.
> Revert "Fix to circumvent pbr related bug in mistral-db-manage populate"

- .kitchen.yml
Follow-up for https://github.com/StackStorm/ansible-st2/pull/115
Since we generate `packagingtest` https://hub.docker.com/r/stackstorm/packagingtest/tags/ Docker images on every push to [st2-dockerfiles](https://github.com/StackStorm/st2-dockerfiles/tree/master/packagingtest) automatically, - switch to new images to test StackStorm installation in Test-Kitchen & Travis.
> Switch to autogenerated 'packagingtest' Docker images

- Vagrantfile
1) Fix:
```
A VirtualBox machine with the name 'ubuntu16' already exists.
Please use another name or delete the machine with the existing
name, and try again.
```
by prefixing `vb.name` with `ansible-st2`.
2) Replace shell provisioner with `ansible_local` to install Ansible on a guest VM (cc @Mierdin).
> Vagrantfile fixes & enhancements

- README.md
See https://github.com/StackStorm/ansible-st2/pull/122 for more details about installing with proxy via Ansible.
> Adding proxy example to the README

- Gemfile
Temporary workaround to pin `kitchen-ansible` version, since recent `0.46.1` https://github.com/neillturner/kitchen-ansible/issues/226#issuecomment-285985937 broke second run of Ansible to test for idempotence.
Build error: https://travis-ci.org/StackStorm/ansible-st2/jobs/210297604
```
bash: -c: line 3: syntax error near unexpected token `&&'
bash: -c: line 3: ` && (echo 'Going to invoke ansible-playbook second time:';           '
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
```
TODO: Revert when the bug is fixed in upstream https://github.com/neillturner/kitchen-ansible/releases
> Fix temporary build failure due to bug in 'kitchen-ansible'

- Gemfile
Reverts StackStorm/ansible-st2#127 since `kitchen-ansible` is fixed in recent versions.
> Revert "Fix temporary build failure due to bug in 'kitchen-ansible'"

- README.md
- roles/st2chatops/tasks/main.yml
- roles/st2smoketests/tasks/main.yml
- roles/st2smoketests/tasks/st2chatops_smoketests.yml
Sample st2chatops role in a playbook:
```
- name: Install StackStorm with all services on a single node
hosts: localhost
roles:
- (......other roles......)
- name: Install st2chatops with "slack" hubot adapter
role: st2chatops
vars:
st2chatops_hubot_adapter: slack
st2chatops_config: {"HUBOT_SLACK_TOKEN":"xoxb-CHANGE-ME-PLEASE"}
st2chatops_version: latest
st2chatops_st2_api_key: CHANGE-ME-PLEASE 
```
> st2_api_key  generation now part of "st2chatops"role and "st2 pack install st2" in smoketests/main.yml

- roles/st2smoketests/tasks/main.yml
This part of a bigger cleanup, removes some dirty hacks we introduced before.
See: https://github.com/StackStorm/st2-packages/issues/429 for more info about improvement in StackStorm services which now should handle readiness/availability natively.
----
`ansible-st2` CI is expected to fail until https://github.com/StackStorm/st2-packages/pull/435 fix will propagate across both `unstable` and `stable` StackStorm repos.
Once the full transition is finished, - we can merge this PR.
> Remove st2 service startup availability workaround

- README.md
- Vagrantfile
With this small change `vagrant up` will setup only `ubuntu16` VM, instead of bringing up entire fleet of 4 machines.
>  Make Ubuntu16 default box for Vagrant

- README.md
- roles/st2web/defaults/main.yml
- roles/st2web/tasks/certificate.yml
- roles/st2web/tasks/main.yml
Closes #132 
Add 2 new vars for `st2web` role: `st2web_ssl_certificate` and `st2web_ssl_certificate_key`.
If both vars are provided, - save the cert. If not provided, - generate self-signed certificate as it was before.
The default behavior remains as before: generting self-signed cert for `st2web` UI,
```yaml
- name: Install StackStorm
hosts: all
roles:
...
- name: Install st2web
role: st2web
vars:
st2web_ssl_certificate: "{{ lookup('file', 'local/path/to/domain-name.crt') }}"
st2web_ssl_certificate_key: "{{ lookup('file', 'local/path/to/domain-name.key') }}"
```
> Add an option to configure custom SSL certificate for st2web/nginx

- roles/bwc/tasks/bwc_repos_setup.yml
- roles/bwc/tasks/license.yml
- roles/st2smoketests/tasks/st2chatops_smoketests.yml
When I execute stackstorm.yml playbook to build StackStorm environment from another (management) node, the following task is failed.
```
TASK [bwc : Read bwc_license_hash from file if it exits] ***********************
[WARNING]: Unable to find '/etc/packagecloud/bwc_license_hash.txt' in expected paths.
fatal: [192.168.100.14]: FAILED! => {"failed": true, "msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /etc/packagecloud/bwc_license_hash.txt"}
to retry, use: --limit @/home/ubuntu/ansible-st2/stackstorm.retry
```
The task of `Read bwc_license_hash from file if it exits` failed to read the `bwc_license_hash_file`. Because the `when` statement checks a condition …
> Fix to make it possible to read file on a remote node

- .travis.yml
- roles/bwc/defaults/main.yml
- roles/bwc/tasks/bwc_repos_setup.yml
- roles/bwc/tasks/main.yml
- stackstorm.yml
Part of the https://github.com/StackStorm/ansible-st2/pull/141 and https://github.com/StackStorm/ansible-st2/pull/143
Check that forked PR CI in Travis really works.
- `st2chatops` role + smoketests should work in forked PR CI
- `bwc` role + smoketests should be skipped for the forked PRs due to license
> Assert that forked PR CI really works

- roles/st2chatops/tasks/main.yml
- roles/st2smoketests/tasks/main.yml
- roles/st2smoketests/tasks/st2chatops.yml
Fixes #145
- Fix st2smoketests for default `shell` adapter, failing in Vagrant env
- ~Use interactive `expect` module which works better comparing to non-interactive `timeout 25 bin/hubot` (hangs early before loading commands when using `shell` adapter)~ (not compatible with `EL6`)
- Use `shell` module + step commands for testing `bin/hubot` 
- ~End-to-end test `!pack get core` chatops command and verify result~ (doesn't work for non-shell adapters)
- Show better error message to user when `st2chatops` couldn't load st2 commands
> Fix 'st2chatops' smoketests for default 'hubot' adapter

- README.md
- roles/bwc/defaults/main.yml
- roles/bwc/tasks/main.yml
- roles/st2/defaults/main.yml
- roles/st2/tasks/main.yml
- roles/st2chatops/defaults/main.yml
- roles/st2chatops/tasks/main.yml
- roles/st2mistral/defaults/main.yml
- roles/st2mistral/tasks/main.yml
- roles/st2web/tasks/main.yml
> Adding present option for version

- .travis.yml
- ansible.cfg
- ansible.cfg.galaxy
- meta/main.yml
As experiment, we've added this repo as [`StackStorm.stackstorm`](https://galaxy.ansible.com/StackStorm/stackstorm/) Ansible Galaxy with all the components  (opposed to https://github.com/StackStorm/ansible-st2/issues/45), see [`meta/main.yml`](https://github.com/StackStorm/ansible-st2/blob/master/meta/main.yml) and `ansible.cfg.galaxy` workaround.
This PR adds a bit better descriptions (mostly for experimental use at the moment) if role was installed from Galaxy. Additionally add `travis.yml` webhook so Ansible Galaxy will show the build status badge.
See: https://www.ansible.com/blog/ansible-galaxy-2-release
> Various Ansible Galaxy cosmetic enhancements

- roles/mongodb/meta/main.yml
- roles/mongodb/tasks/mongodb_apt.yaml
- roles/mongodb/tasks/mongodb_yum.yaml
Part of https://github.com/StackStorm/st2/issues/3592 change.
Since we don't have per version branching in please yet, we should only merge this after v2.4.0 is out.
> Install MongoDB 3.4 by default

- .travis.yml
Add Slack notifications per https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications
This will post build failures to '#ansible' channel in 'stackstorm-community' Slack
>  Add Slack notifications on CI failures

- roles/st2chatops/tasks/main.yml
Make sure we restart `st2chatops` service once the package was installed and more important, - upgraded.
> Fix restart 'st2chatops' on package install/upgrade

- roles/st2chatops/tasks/main.yml
This fixes the build failure https://travis-ci.org/StackStorm/ansible-st2/jobs/277766176 for `Ubuntu14` and `Ubuntu16` which rely on updated `Ansible 2.4`, while EL6/7 are still on `Ansible 2.3`.
Diff for task results between Ansible 2.3 and 2.4:
```diff
-ok: [Ansible 2.3] => {
+ok: [Ansible 2.4] => {
"task_apikey_exists": {
"changed": false, 
"cmd": [
"grep", 
"-e", 
"^export ST2_API_KEY=\"\\${ST2_API_KEY}\"$", 
"/opt/stackstorm/chatops/st2chatops.env"
], 
"delta": "0:00:00.002443", 
"end": "2017-09-21 11:45:23.233013", 
+       "failed": false,
"rc": 0, 
"start": "2017-09-21 11:45:23.230570", 
"stderr": "", 
"stderr_lines": [], 
"stdout": "export ST2_API_KEY=\"${ST2_API_KEY}\"", 
"stdout_lines": [
"export ST2_API_KEY=\"${ST2_API_KEY}\""
]
}
}
```
With that, relying on …
> Fix 'st2chatops' not adding st2 API key with Ansible 2.4

- ansible.cfg.galaxy
- meta/main.yml
Update the path in example `ansible.cfg` to point to `StackStorm.stackstorm` when installing from Galaxy https://galaxy.ansible.com/StackStorm/stackstorm/
> Update roles path in example ansible.cfg when installing StackStorm from galaxy

- roles/bwc/tasks/rbac.yml
The directory creation and permissions/ownership is done by the deb/rpm packaging now.
The build will :white_check_mark: once the change is merged in upstream.
> Remove BWC RBAC directories creation

- roles/st2mistral/tasks/main.yml
When upgrading mistral, the database needs to be updated as well.
This adds the version number to the signal file so that on upgrade,
it will run the 'upgrade head' and 'populate' commands again.
> Make sure mistral db gets upgraded too

- roles/st2/handlers/main.yml
- roles/st2/tasks/main.yml
- roles/st2/tasks/proxy.yml
Closes #178 
Enable configuring proxy settings for StackStorm services when `proxy` environment variables are set.
See: https://docs.stackstorm.com/latest/packs.html#proxy-configuration-via-environment-variables for what's exactly configured
This is required for `st2 pack install` work via proxy.
> Configure proxy settings for stackstorm services

- roles/st2mistral/tasks/main.yml
The task is not necessary since https://github.com/StackStorm/st2-packages/pull/518 `st2python` dependency is included in rpm packaging for `st2mistral`.
> Remove explicit st2python <> st2mistral dependency under EL6

- roles/st2mistral/tasks/main.yml
Use dbname+drivername as described in StackStorm/st2-packages#490.
Related:
StackStorm/st2-packages#491
StackStorm/st2-docker#64
> Add drivername to mistral database connection string

- roles/st2chatops/tasks/main.yml
- roles/st2smoketests/tasks/main.yml
Passwords with spaces were passed incorrectly because of missing quotes. This caused the executed command to fail as the space separated parts were each used as argument instead of as one argument.
> st2chatops: allow auth passwords with spaces in "st2 auth" command

- roles/bwc/tasks/bwc_repos_apt.yml
- roles/bwc/tasks/bwc_repos_setup.yml
- roles/bwc/tasks/bwc_repos_yum.yml
- roles/bwc/tasks/main.yml
- roles/epel/tasks/main.yml
- roles/mongodb/tasks/mongodb_apt.yml
- roles/mongodb/tasks/mongodb_yum.yml
- roles/nginx/tasks/nginx_apt.yml
- roles/nginx/tasks/nginx_yum.yml
- roles/nodejs/tasks/nodejs_apt.yml
- roles/nodejs/tasks/nodejs_yum.yml
- roles/postgresql/tasks/postgresql_apt.yml
- roles/postgresql/tasks/postgresql_yum6.yml
- roles/postgresql/tasks/postgresql_yum7.yml
- roles/rabbitmq/tasks/main.yml
- roles/st2/tasks/auth.yml
- roles/st2/tasks/main.yml
- roles/st2chatops/tasks/main.yml
- roles/st2mistral/tasks/main.yml
- roles/st2repo/tasks/st2repo_apt.yml
- roles/st2repo/tasks/st2repo_yum.yml
- roles/st2web/tasks/main.yml
Closes #151 (Retry logic for the connection-oriented commands)
The most-frequent random error when installing StackStorm is related to downloading packages or similar download-oriented operations (connection closed, 50X, SSL broken pipe, GnuTLS recv error, etc). All temporary.
Adding retry on failure logic where applicable.
> Add task retries in case of connection failure

- roles/st2/vars/main.yml
Closes #196
Added st2workflowengine to the list of services for 2.8.0 release
> Added st2workflowengine

- .kitchen-docker/centos6/Dockerfile
This is an optimization for tests that run on Travis.
Got this error when beginning the second suite of tests
> The job exceeded the maximum log length, and has been terminated.
Other platforms do not have as many progress bars.
Compare these build logs to see why the YUM Progress bars are so
problematic.
without this change:
https://api.travis-ci.org/v3/job/430822100/log.txt
with this change:
https://api.travis-ci.org/v3/job/431074530/log.txt
Look below the line that includes:
>   Retrieving https://dl.fedoraproject.org/pub/epel
You will see pages and pages of useless epel/other download progress bars.
> Lower yum log level to avoid travis log length limit on centos-6

- test/integration/default.yml
- test/integration/default/default.yml
This makes sure that when any new test suites get added, they all use
the same playbook (stackstorm.yml) by default, no matter what the test
suite is named. If the suite needs a different playbook, the override
can be placed in test/integration/<suite name>/default.yml
> Multiple kitchen test suites default to same playbook

- roles/mongodb/tasks/mongodb_auth.yml
This adds a stub tasks file for adding auth to mongo. Currently, it is not imported/included anywhere.
We'll only include/import this once we're satisfied that it is complete and ready to use.
The only task in this stub file so far is adding pymongo, a dep of the mongodb_user ansible module.
Ansible [docs](https://docs.ansible.com/ansible/2.4/mongodb_user_module.html) mention (in the comment to an example near the end) that
pymongo 2.5+ is supported, so system level packages work for all
platforms.
- CentOS 6 -> EPEL -> python-pymongo-2.5.2
- CentOS 7 -> EPEL -> python-pymongo-2.5.2
- Ubuntu 14.04 -> python-pymongo_2.6.3
- Ubuntu 16.04 -> python-pymongo_3.2
> Add pymongo, a dep of mongodb_user ansible module

- roles/bwc/tasks/license.yml
https://circleci.com/gh/StackStorm/ansible-st2/649
Fixing 
```
Examining roles/st2/tasks/config.yml of type playbook
[102] No Jinja2 in when
/root/project/roles/bwc/tasks/license.yml:35
Task/Handler: Cleanup read token cached file from disk
[102] No Jinja2 in when
/root/project/roles/bwc/tasks/license.yml:47
Task/Handler: Write new bwc_license_hash to file
Exited with code 2
```
As seen in https://github.com/StackStorm/ansible-st2/pull/208
> Fix ansible-lint warnings about using Jinja expressions in 'when'

- roles/bwc/tasks/bwc_repos_apt.yml
- roles/mongodb/tasks/mongodb_apt.yml
- roles/mongodb/tasks/mongodb_yum.yml
- roles/postgresql/tasks/postgresql_apt.yml
- roles/postgresql/tasks/postgresql_yum6.yml
- roles/postgresql/tasks/postgresql_yum7.yml
- roles/st2/tasks/auth.yml
- roles/st2repo/tasks/st2repo_apt.yml
This PR fixes two issues:
1. Referenced in issue: https://github.com/StackStorm/ansible-st2/issues/203
2. Use state=present instead of state=installed for apt/yum module.
Closes #203
> Fix deprecated warnings with Ansible 2.7

- roles/st2mistral/tasks/main.yml
The use of `when mistral_install_latest|changed` is now [deprecated](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#jinja-tests-used-as-filters).
This should be `when mistral_install_latest is changed`
Looks like this will require a minimum Ansible version of 2.5, but this is also the oldest version supported by upstream. We should plan to change our [minimum Ansible version to 2.5](https://github.com/StackStorm/ansible-st2/issues/190).
> Changed use of Jinja filters as tests

- roles/st2/tasks/main.yml
- roles/st2/tasks/version.yml
- roles/st2/vars/main.yml
Closes #207 
This PR adds new service `st2scheduler`, introduced since StackStorm `v3.0`.
This time as absence of the new service fails the build, need to implement version-dependent logic (originally proposed by @cognifloyd) when specific services are selected depending on installed StackStorm version.
> Add new service 'st2scheduler', implement st2-version dependent logic

- roles/st2/tasks/version.yml
The current state of Ansible-st2 plays is that they're compatible (tested) with Ansible `v2.3.0`, except of this tiny test https://docs.ansible.com/ansible/2.5/user_guide/playbooks_tests.html#version-comparison
This PR makes sense to release latest `v2.3.0`-compatible play via `v0.8.9` before bumping min Ansible to `v2.5.0` as part of #190 and `v0.9.0` release.
> Use older 'version_compare' jinja test, compatible with Ansible before v2.5.0

- roles/st2/tasks/version.yml
As seen in `ansible-pull` environment, version `2.5.10`.
```
TASK [st2 : Redefine list of services based on st2 version] ********************
fatal: [slack-relay001.uswest2.stackstorm.net]: FAILED! => {"msg": "The conditional check 'item.key is version_compare(st2_version_installed, '<=')' failed. The error was: error while evaluating conditional (item.key is version_compare(st2_version_installed, '<=')): 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/etc/ansible/roles/StackStorm.stackstorm/roles/st2/tasks/version.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Injecting 'st2_services' var in the middle of play verified to work with 'restart st2' handler as handlers …
```
> Fix 'get installed st2 version' task not being run properly in some Ansible versions

- roles/st2/vars/main.yml
Release version has been rollbacked from 3.0 to 2.10 due to project management decision.
> Rollback release version from 3.0 to 2.10

- roles/bwc/vars/enterprise.yml
- roles/nodejs/tasks/main.yml
- roles/nodejs/vars/stable.yml
- roles/st2repo/vars/stable.yml
This PR updates the stable repository public key IDs for the
enterprise and stable repos in packagecloud. This is a required change
following packagecloud GPG changes.
> Update stable repo keys

- .circleci/config.yml
- roles/bwc/meta/main.yml
- roles/bwc/tasks/bwc_repos_setup.yml
- roles/bwc_smoketests/meta/main.yml
- roles/epel/meta/main.yml
- roles/mongodb/meta/main.yml
- roles/nginx/meta/main.yml
- roles/nodejs/meta/main.yml
- roles/postgresql/meta/main.yml
- roles/rabbitmq/meta/main.yml
- roles/st2/meta/main.yml
- roles/st2/tasks/proxy.yml
- roles/st2chatops/meta/main.yml
- roles/st2chatops/tasks/main.yml
- roles/st2mistral/meta/main.yml
- roles/st2repo/meta/main.yml
- roles/st2web/meta/main.yml
`ansible-lint` 4.0.0 introduces many new default rules. These trip us up in many places. 
The only new default rule I have not fixed is the 120-char line length rule. For now I have just excluded that rule from checks.
I have also fixed a small issue with our CircleCi config, where it was running ansible-lint against non-existent `*.yaml` files.
> New linting rules

- .circleci/config.yml
- .kitchen.yml
- .yamllint
- roles/postgresql/tasks/postgresql_yum6.yml
- roles/st2/tasks/datastore.yml
YAML lint check is now recommended as Ansible Galaxy roles are scored based on set of automated verifications.
* https://galaxy.ansible.com/docs/contributing/content_scoring.html  - rules
* https://galaxy.ansible.com/StackStorm/stackstorm - where StackStorm roles are evaluated
This should fix the StackStorm role rating at Ansible Galaxy.
> Add YAML lint checks

- meta/main.yml
- roles/ewc/meta/main.yml
- roles/st2/meta/main.yml
- roles/st2chatops/meta/main.yml
- roles/st2mistral/meta/main.yml
- roles/st2repo/meta/main.yml
Cosmetic change that adds `system` tag to the list of Galaxy tags to make sure StackStorm role is present within one of the features categories at https://galaxy.ansible.com/home
> Add Ansible Galaxy 'system' tag

- meta/main.yml
A missing cosmetic change that bumps minimum Ansible version to `v2.5` to show correctly in Galaxy: https://galaxy.ansible.com/StackStorm/stackstorm
> Bump minimum Ansible version to 2.5 in Galaxy

- roles/ewc/tasks/ewc_repos_apt.yml
https://github.com/StackStorm/ansible-st2/pull/215 updated the ansible facts namespace to `ansible_facts.<blah>`, rather than `ansible_<blah>`.
Looks like we missed a couple of references in one single task.
> Ansible_facts namespacing

- .circleci/config.yml
- roles/StackStorm.ewc/tasks/ewc_repos_apt.yml
- roles/StackStorm.ewc/tasks/ewc_repos_cleanup_apt.yml
- roles/StackStorm.ewc/tasks/ewc_repos_cleanup_yum.yml
- roles/StackStorm.ewc/tasks/ewc_repos_yum.yml
- roles/StackStorm.ewc/tasks/ldap.yml
- roles/StackStorm.ewc/tasks/license.yml
- roles/StackStorm.ewc/tasks/rbac.yml
- roles/StackStorm.nginx/tasks/nginx_yum.yml
- roles/StackStorm.postgresql/tasks/postgresql_yum6.yml
- roles/StackStorm.postgresql/tasks/postgresql_yum7.yml
- roles/StackStorm.st2smoketests/tasks/st2chatops.yml
`ansible-lint` recently introduced a few more checks which made our CI to fail.
Update the code to rely on linter updates.
> Fix ansible-lint CI failures

- .travis.yml
- stackstorm.yml
Fix CI failures for forked builds.
TravisCI changed behavior and stopped sharing secrets with forked CI environments.
This PR excludes Enterprise builds for community contributions.
> Fix TravisCI failures for forked builds (contributions)

- stackstorm.yml
Closes #237 
Under some circumstances `ewc_license` could be `None` in `stackstorm.yml` Ansible play
Fixes:
>fatal: [ubuntu16]: FAILED! => {"msg": "The conditional check 'ewc_license is defined and ewc_license | length > 0' failed. The error was: Unexpected templating type error occurred on ({% if ewc_license is defined and ewc_license | length > 0 %} True {% else %} False {% endif %}): object of type 'NoneType' has no len()\n\n"}
> Fix 'ewc_license' conditional check in stackstorm.yml example play

- roles/StackStorm.st2/tasks/config.yml
- roles/StackStorm.st2mistral/tasks/config.yml
Closes #238 
Covers edge case when user wants to set in st2.conf json-formatted value which might be converted to particular structure during the jinja/ansible pipeline.
See https://github.com/StackStorm/ansible-st2/issues/156
> Ensure st2.conf values are not converted to particular structure

- roles/StackStorm.st2/tasks/proxy.yml
Otherwise it can't connect to RTM on Slack, for example.
> st2chatops also may need proxies

- stackstorm.yml
A quick, clean and simple way to bring in proxy support, rather than needing to run a forked version of the playbook.
> Bring in proxy env vars if defined as Ansible vars

- roles/StackStorm.st2/tasks/proxy.yml
- roles/StackStorm.st2chatops/tasks/main.yml
- stackstorm.yml
Reverts StackStorm/ansible-st2#239
Move proxy settings for Chatops to respective `StackStorm.st2chatops` role from `StackStorm.st2`.
> Move proxy settings for Chatops to respective `StackStorm.st2chatops` role

- roles/StackStorm.ewc/tasks/license.yml
Fixes build failure (https://travis-ci.org/StackStorm/ansible-st2/jobs/533578756#L1759) appeared when running under newly released Ansible `2.8.0`:
```
{"reason": "'become' is not a valid attribute for a TaskInclude\n\nThe error appears to be in '/tmp/kitchen/roles/StackStorm.ewc/tasks/license.yml': line 59, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Cleanup repo list file from disk\"\n  ^ here\n"}
```
> Fix compatibility with new Ansible 2.8.0

- roles/StackStorm.rabbitmq/tasks/main.yml
- roles/StackStorm.st2/tasks/auth.yml
- roles/StackStorm.st2/tasks/user.yml
Resolve a couple more deprecation warnings, e.g.
```
TASK [StackStorm.st2 : user | Disable requiretty] *************************************************************************************************************************
[DEPRECATION WARNING]: evaluating st2_system_user_in_sudoers as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the
future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```
> Explicit mark variable as bool

- roles/StackStorm.st2smoketests/tasks/main.yml
Attempts to fix #251
I have not added any tests.
I am also unsure why there is a condition just for red hat version 6 to install the st2 pack but the next task to `Verify if st2 pack was installed` has no such condition.
> Include centos 7 in condition for installing st2 pack in smoketests

- roles/StackStorm.mongodb/tasks/mongodb_auth.yml
This PR is preparation for enabling mongo auth via the ansible playbook.
These tasks will not be activated until all required tasks are committed.
This installs pip via system package, and then pymongo via pip.
pymongo is needed for mongodb_user module to enable mongo auth.
pymongo 3.2+ is required to work with mongo 3.2+
system packages are too old on all but Ubuntu 16:
- 2.5.2 on EL 6 and EL 7
- 2.6.3 on Ubuntu 14 Trusty
- 3.2 on Ubuntu 16 Xenial
> Mongo Auth | Intall pymongo via pip (vs via sys pkgs)

- roles/StackStorm.nodejs/tasks/nodejs_yum.yml
Add some tasks to ensure the nodesource repo is up-to-date before attempting to install nodejs.
Thus, if this playbook is run against a machine that already has the repo, it will safely upgrade
the repo so that the nodejs install task doesn't complain about not finding the version requested.
This also sets update_cache on upgrade so that the newer nodejs rpm becomes available for install.
> Use yum_repository for nodesource repo install

- .kitchen.yml
- .travis.yml
- README.md
- Vagrantfile
- meta/main.yml
- roles/StackStorm.ewc/meta/main.yml
- roles/StackStorm.ewc_smoketests/meta/main.yml
- roles/StackStorm.mongodb/meta/main.yml
- roles/StackStorm.nginx/meta/main.yml
- roles/StackStorm.nodejs/meta/main.yml
- roles/StackStorm.postgresql/meta/main.yml
- roles/StackStorm.rabbitmq/meta/main.yml
- roles/StackStorm.st2/meta/main.yml
- roles/StackStorm.st2chatops/meta/main.yml
- roles/StackStorm.st2mistral/meta/main.yml
- roles/StackStorm.st2repo/meta/main.yml
- roles/StackStorm.st2web/meta/main.yml
Closes #246
Remove `ubuntu trusty` which was dropped since st2 `v3.2.1`
> [#246]  Drop Ubuntu Trusty support

- .kitchen.yml
- .travis.yml
- README.md
- Vagrantfile
- meta/main.yml
- roles/StackStorm.ewc/meta/main.yml
- roles/StackStorm.ewc_smoketests/meta/main.yml
- roles/StackStorm.mongodb/meta/main.yml
- roles/StackStorm.nginx/meta/main.yml
- roles/StackStorm.nodejs/meta/main.yml
- roles/StackStorm.rabbitmq/meta/main.yml
- roles/StackStorm.st2/meta/main.yml
- roles/StackStorm.st2chatops/meta/main.yml
- roles/StackStorm.st2repo/meta/main.yml
- roles/StackStorm.st2web/meta/main.yml
- stackstorm.yml
Resolves https://github.com/StackStorm/ansible-st2/issues/249
st2mistral role has an added conditional so it doesn't run when on Ubuntu18.04.  This is also applied to the postgresql role dependency.
Ubuntu18.04 added to the virtual machine list in the vagrant file and a small update to the readme to note that Ubuntu 18.04 is available as vagrant box.
> Support for Ubuntu 18.04

- .circleci/config.yml
- stackstorm.yml
Recent change to RBAC in `stackstorm/st2` master broke the EWC install for unstable packages resulting in failed builds (https://travis-ci.org/github/StackStorm/ansible-st2/jobs/730839457).
In this PR I'm just disabling the EWC installation and testing for unstable repositories by setting the `BWC_LICENSE_ENTERPRISE_UNSTABLE` ENV variable to 0.
We should however migrate the EWC role in the future st2 releases as part of https://github.com/StackStorm/ansible-st2/issues/260.
> Disable EWC install for unstable packages

- roles/StackStorm.nginx/vars/redhat.yml
- roles/StackStorm.st2/tasks/main.yml
Updates for playbooks to install the libselinux-python3 module on EL 7
Updates for playbooks to check that python3-devel is available. If not available then locate the optional server repo and install python3-devel RPM from there. Needed for RHEL where python3-devel is in a disabled repo, and therefore will not get pulled in automatically as a dependency when st2 rpm is installed.
Part of StackStorm/discussions#54
> Ansible changes for RH 7 and Python3

- README.md
- roles/StackStorm.st2/defaults/main.yml
- roles/StackStorm.st2/tasks/main.yml
Currently, if using these roles/playbooks to install StackStorm and you want to install a new auth backend or coordination backend, you will most likely need to install some python modules into the `/opt/stackstorm/st2` virtualenv to make it work.
Example, if you want to enable the coordination service and use the`redis` backend, you need to install the `redis` python module into the `/opt/stackstorm/st2` virtualenv.
This PR adds a new variable `st2_python_packages` that accepts a list of python modules to install.
> Ability to install addition pip modules into the st2 virtualenv

- roles/StackStorm.st2/vars/main.yml
This PR fixes CI build failure in the current `master` branch.
A follow-up to https://github.com/StackStorm/st2-packages/pull/683 where `st2resultstracker` service was removed from the packages.
> Remove st2resultstracker, deprecated since st2 v3.3.0

- README.md
- roles/StackStorm.st2/defaults/main.yml
- roles/StackStorm.st2/tasks/main.yml
- roles/StackStorm.st2/tasks/request_ppa.yml
Updates to scripts that if Python 3.6 is unavailable on Ubuntu 16 to ask user if they want to install the Deadsnakes PPA.
User can automatically give permission for installation from Deadsnakes PPA  by passing variable st2_u16_add_insecure_py3_ppa with value true
> Updates for Ubuntu 16 and Python 3

- README.md
Remove reference to Chef as an alternative installer, as the Chef Cookbook has been deprecated.
> Remove Chef from ansible documentation, as it is deprecated

- .circleci/config.yml
- roles/StackStorm.rabbitmq/defaults/main.yml
- roles/StackStorm.rabbitmq/tasks/main.yml
- roles/StackStorm.rabbitmq/vars/main.yml
Since rabbitmq-server 3.8.13 was released, installations on EL8 failed as we install latest rabbitmq from rabbitmq packagecloud, But 3.8.13 requires version of erlang that is not in the EL8 or EPEL repositories.
This PR makes the same changes to the ansible scripts as performed by bash installer in https://github.com/StackStorm/st2-packages/pull/693
> Pin rabbitmq version on EL8

- roles/StackStorm.rabbitmq/defaults/main.yml
- roles/StackStorm.rabbitmq/tasks/main.yml
- roles/StackStorm.rabbitmq/vars/main.yml
Stop pinning version of rabbitmq on EL8.
Install latest from packagecloud, and therefore as that requires newer version of erlang, install the minimal erland provided by rabbitmq - as per instructions at https://github.com/rabbitmq/erlang-rpm
Relates to https://github.com/StackStorm/st2-packages/pull/699
> Unpin rabbitmq

- roles/StackStorm.epel/tasks/main.yml
Closes https://github.com/StackStorm/ansible-st2/issues/292
Not sure why this has started to fail recently. But downloaded the key first, ensures that it downloads successfully.
On bash installers as we use -y then it will install without issue
> Download GPG key explicitly

- README.md
- roles/StackStorm.st2/defaults/main.yml
- roles/StackStorm.st2/tasks/main.yml
- roles/StackStorm.st2chatops/tasks/main.yml
- roles/StackStorm.st2web/defaults/main.yml
- roles/StackStorm.st2web/tasks/main.yml
Currently the playbooks do not work if you want to specify a particular version of ST2.
The problems were:
- wrong check on using = or - as separately, as logic was if yum else do ... But newer EL are dnf - and so were using the apt separator
- st2_version was used for both st2 and st2web packages. And if specified always had to specify st2_revision. This only works if the same revision exists for both packages, but this isn't necessarily the case e.g. 3.4.0 has 3.4.0-1 for st2, and 3.4.0-3 on st2web
- On EL systems then there is no need to specify revisions, if use 3.4.0 it would give the latest version. But on Debian the revision needs to be specified
- st2chatops was insatlled differntly with a single st2chatops_version that could be used as with or without revision
These issues were …
> Fix problem installing specific version of ST2

- README.md
- roles/StackStorm.nodejs/defaults/main.yml
There were different ways to realize the node 14 support but this one is the only one that's not breaking. 
Changing just the default would break deployments of older releases even though we may mention it on the README. 2nd challenge was that a simple comparison with the ansible version test is not able to work with `latest` as st2_version. That's why we use an if-elsif-else and not just an if-else clause here.
> Add support for nodejs 14 and list the variable on the README

- roles/StackStorm.mongodb/tasks/mongodb_debian.yml
- roles/StackStorm.st2/tasks/version.yml
Fixes #304 (at least the first problem).
> Install gpg before calling apt_key

- README.md
Fixes #306; ~adding `markdownlint` to CI as well~.
> Markdown linting README.md

- roles/StackStorm.rabbitmq/defaults/main.yml
- roles/StackStorm.rabbitmq/tasks/rabbitmq_redhat.yml
Install on EL8 started to fail on RabbitMQ install. Problems reported "please re-compile this module with an Erlang/OTP 25 compiler"
Erlang 25 has been pushed to the RabbitMQ erlang repository, but according to https://www.rabbitmq.com/which-erlang.html erlang 25 support is preview.
Update so that erlang version can be specified, and make the default value 24* so do not pick up 25.
> Allow Erlang version on EL8 to be pinned, and by default use < 25

- roles/StackStorm.rabbitmq/defaults/main.yml
- roles/StackStorm.rabbitmq/tasks/rabbitmq_debian.yml
- roles/StackStorm.st2/tasks/auth.yml
Use the CloudSmith rabbitmq-erlang packages rather than the LaunchPad  erlang packages for Debian installations, so that we can specify a 24.x version of the rabbitmq-erlang. (25.x and 22.x are only available in LaunchPad for Debian and fail with latest rabbitMQ).
We no-longer want to use the latest 1.25 that is available in the rabbitmq-erlang repository, as this means that rabbitmq fails to install, and instead reports error:
```
fatal: [localhost]: FAILED! => {"attempts": 5, "cache_update_time": 1653987046, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'rabbitmq-server'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: …
```
> Use version of erlang < 1.25 and fix EL8 passlib

- .kitchen-docker/rockylinux8/Dockerfile
kitchen ansible provider always tries to install ansible, but that is no-longer available on EL8. 
Updated the el8 dockerfile to install ansible-core and the necessary collections that were in the old ansible package but not in ansible-core.
> Need to install ansible-core on EL8

- .github/workflows/build.yaml
Update the deprecated action `actions/setup-ruby@v1` to `ruby/setup-ruby@v1`. Upgrade `actions/checkout`, `actions/cache`, and `technote-space/workflow-conclusion-action` for the Node 12 (in favor of 16) deprecation. Looks like I was running into "rate limiting" ... I pushed `max-parallel: 1` as a shot in the dark.
> Update and upgrade deprecated actions

- .github/workflows/build.yaml
- .markdownlint.yml
- README.md
Fix the broken Slack badge image, remove contractions, make grammar changes, write OS names and versions more consistently, show long options in commands, etc. I'll add markdown linting ~in another PR~ shortly.
> Refresh the `README.md`
